name: Deploy documentation

on:
    push:
        branches:
            - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Create documentation with Doxygen
        uses: mattnotmitt/doxygen-action@v1

      - name: Deploy html to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: ./docs/html
    